[project]
name = "analise-deadfish"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dateparser>=1.2.0",
    "httpx>=0.28.1",
    "parsel>=1.9.1",
    "polars>=1.17.1",
]
